consul:
    image: gliderlabs/consul-server
    net: host 
    command: -bootstrap

redis:
    image: redis
    ports: 
      - 6379

registrator:
    image: gliderlabs/registrator
    net: host
    volumes: 
      - /var/run/docker.sock:/tmp/docker.sock
    command: consul://127.0.0.1:8500

app:
    build: .
    links:
      - redis

lb:
    image: andrexus/nginx-consul-template
    ports:
      - 8000
    volumes:
      - ./consul-template.cfg:/etc/consul-template/config.cfg
      - ./nginx-template.conf:/etc/consul-template/templates/sites.ctmpl
      - ./hosts:/etc/hosts
    links:
      - app