consul:
    image: gliderlabs/consul-server
    #net: host 
    command: -bootstrap

redis:
    image: redis
    ports: 
      - 6379

registrator:
    image: gliderlabs/registrator
    #net: host
    volumes: 
      - /var/run/docker.sock:/tmp/docker.sock
    command: consul://consul:8500
    links:
      - consul

app:
    build: .
    ports: 
      - 5000 
    links:
      - consul
